version: '3.8'

services:
  web:
    image: julianew2/django-dock:django-docker_web
    container_name: django
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  nginx:
    image: julianew2/django-dock:django-docker_nginx
    container_name: nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./app/static/:/usr/src/app/static/
      - ./app/media/:/usr/src/app/media/

  db:
    image: postgres:13.0-alpine
    container_name: postgres_db
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


volumes:
  postgres_data: